@echo off
color 0a
title Development Server. Starting Development Server... This may take a few seconds... Please wait...
echo Starting Development Server...
echo This may take a few seconds...
echo Please wait...
cd /d "C:\Websites\Hovedforløb\nightbird"
start .
code . && start http://localhost:3000 && npm run dev

